// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'todoApp';

  // State
  todos: string[] = [];
  todoText = '';

  // SideEfects
  ngOnInit() {
    const Todos = localStorage.getItem('todos');
    this.todos = JSON.parse(Todos as string) || [];
  }

  // Function
  pushTodo() {
    this.todos.push(this.todoText);
    localStorage.setItem('todos', JSON.stringify(this.todos));
    this.todoText = '';
  }
}

<ul>
  <li *ngFor="let todo of todos">{{ todo }}</li>
</ul>

<form (ngSubmit)="pushTodo()">
  <input name="todoText" [(ngModel)]="todoText" />
  <input type="submit" value="Add Todo" />
</form>

// react-js/src/App.js
import { useEffect, useRef, useState } from "react";
import "./App.css";

function App() {
  // State
  const [todos, setTodos] = useState([]);

  // Binding
  const todoText = useRef();

  // Side Effects
  useEffect(() => {
    const Todos = localStorage.getItem("todos");
    setTodos(Todos ? JSON.parse(Todos) : []);
  }, []);

  // Function
  function pushTodo(event) {
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem("todos", JSON.stringify(next));
    todoText.current.value = "";
  }

  return (
    <div>
      <ul>
        {todos.map((todo) => (
          <li key={todo}>{todo}</li>
        ))}
      </ul>
      <form onSubmit={pushTodo}>
        <input type="text" ref={todoText} />
        <input type="submit" value="Add Todo" />
      </form>
    </div>
  );
}

export default App;
